name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # lets you trigger manually too

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Build site
        run: |
          python build.py \
            --site_url "https://calcifergtp-glitch.github.io/my-test-site" \
            --brand "My Test Blog" \
            --amazon_tag "yourtag-20" \
            --keywords_file data/keywords.json \
            --audience "home cooks in US" \
            --author_name "SiteSmith Bot" \
            --author_url "https://calcifergtp-glitch.github.io/my-test-site/about.html" \
            --author_bio "Automated blog powered by SiteSmith GPT."

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
